# Generated by Django 5.1.1 on 2024-09-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=20)),
                ('password', models.TextField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
