# Generated by Django 5.1.1 on 2024-09-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_user_managers_user_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
