# Generated by Django 5.1.1 on 2024-09-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_task_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AddField(
            model_name='task',
            name='task_desc',
            field=models.TextField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_name',
            field=models.CharField(default='Nova Tarefa', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.TextField(default='Pendente', max_length=12),
        ),
    ]
