# Generated by Django 5.1.1 on 2024-09-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_task_id_task_task_desc_task_task_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(default='Nova Tarefa', max_length=100),
        ),
    ]
