# Generated by Django 5.1.1 on 2024-09-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_task_task_id_alter_task_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_id',
        ),
        migrations.AddField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
